from __future__ import annotations

import json
import re
from typing import Any

from .cidr import cidr_to_dhcpd
from .models import DhcpConfig

GLOBAL_DIRECTIVES = {
    "default-lease-time",
    "max-lease-time",
    "min-lease-time",
    "authoritative",
    "ddns-update-style",
    "log-facility",
}


def _is_empty_option_value(value: Any) -> bool:
    return value is None or value == "" or value == []


def _format_option_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return ", ".join(_format_option_value(v) for v in value)
    if isinstance(value, str):
        if re.match(r"^[\d.]+$", value):
            return value
        return f'"{value}"'
    return json.dumps(value)


def _write_options(lines: list[str], options: dict[str, Any], indent: str = "  ") -> None:
    for key, value in options.items():
        if key in GLOBAL_DIRECTIVES or _is_empty_option_value(value):
            continue
        lines.append(f"{indent}option {key} {_format_option_value(value)};")


def _write_global_directives(lines: list[str], options: dict[str, Any]) -> None:
    for key in ("default-lease-time", "max-lease-time", "min-lease-time"):
        if key in options and not _is_empty_option_value(options[key]):
            lines.append(f"{key} {_format_option_value(options[key])};")
    for key, value in options.items():
        if key in GLOBAL_DIRECTIVES or key in {"default-lease-time", "max-lease-time", "min-lease-time"}:
            continue
        if _is_empty_option_value(value):
            continue
        lines.append(f"option {key} {_format_option_value(value)};")


def generate_dhcpd_conf(config: DhcpConfig) -> str:
    lines: list[str] = [
        "# Generated by DHCP UI (DUI)",
        f"log-facility {config.log_facility};",
    ]

    if config.ddns_update_style:
        lines.append(f"ddns-update-style {config.ddns_update_style};")

    if config.authoritative:
        lines.append("authoritative;")

    for definition in config.option_definitions:
        lines.append(definition)

    if config.global_options:
        lines.append("")
        _write_global_directives(lines, config.global_options)

    for subnet in config.subnets:
        addr, mask = cidr_to_dhcpd(subnet.network)
        lines.extend(["", f"subnet {addr} netmask {mask} {{"])
        if subnet.range:
            lines.append(f"  range {subnet.range.start} {subnet.range.end};")
        _write_options(lines, subnet.options)
        lines.append("}")

    for host in config.hosts:
        lines.extend(["", f"host {host.name} {{"])
        lines.append(f"  hardware ethernet {host.hardware_address};")
        lines.append(f"  fixed-address {host.fixed_address};")
        _write_options(lines, host.options)
        lines.append("}")

    lines.append("")
    return "\n".join(lines)
