services:
  dui:
    build: .
    container_name: dui
    # for windows hosts to test, comment line below and uncomment ports section
    network_mode: host
    # ports:
    #   - 8067:8067/tcp
    #   - 67:67/udp
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - dui-data:/data
    environment:
      DUI_INTERFACE: eth0
      DUI_HTTP_PORT: 8067
      DUI_SERVER_NAME: "DHCP UI (DUI)"
    restart: unless-stopped

volumes:
  dui-data:
